package storage

var schemaStatements = []string{
	"PRAGMA auto_vacuum=INCREMENTAL",
	`create table schema_migrations(version text primary key, applied_at timestamp not null)`,
	`create table config_sources(config_source_id text primary key, source_key text not null unique, path text not null, priority integer not null, created_at timestamp not null, disabled_at timestamp null)`,
	`create table config_revisions(config_revision_id text primary key, config_source_id text not null references config_sources(config_source_id), content_hash text not null, effective_config_json json not null, loaded_at timestamp not null)`,
	`create table projects(project_id text primary key, project_key text not null unique, display_name text not null, root_path text not null, default_base_ref text not null, default_worktree_mode text not null, managed_worktree_root_path text not null, created_at timestamp not null, archived_at timestamp null)`,
	`create table repositories(repository_id text primary key, repository_key text not null unique, origin_url text null, git_common_dir_path text not null, default_branch_ref text not null, created_at timestamp not null, archived_at timestamp null)`,
	`create table project_repositories(project_repository_id text primary key, project_id text not null references projects(project_id), repository_id text not null references repositories(repository_id), role text not null, created_at timestamp not null)`,
	`create table hosts(host_id text primary key, host_key text not null unique, display_name text not null, access_spec_json json not null, created_at timestamp not null, archived_at timestamp null)`,
	`create table agent_providers(provider_id text primary key, provider_key text not null unique, display_name text not null, command_path text not null, provider_config_json json not null, created_at timestamp not null, disabled_at timestamp null)`,
	`create table provider_models(provider_model_id text primary key, provider_id text not null references agent_providers(provider_id), model_key text not null, provider_model_name text not null, model_spec_json json not null, created_at timestamp not null, retired_at timestamp null)`,
	`create table agent_profiles(profile_id text primary key, profile_key text not null unique, display_name text not null, created_at timestamp not null, archived_at timestamp null)`,
	`create table agent_profile_revisions(profile_revision_id text primary key, profile_id text not null references agent_profiles(profile_id), revision_seq integer not null, provider_id text not null references agent_providers(provider_id), provider_model_id text null references provider_models(provider_model_id), effort_key text null, permission_policy_json json not null, runtime_limits_json json not null, extra_args_json json not null, created_at timestamp not null)`,
	`create table agent_profile_current_revisions(profile_id text primary key references agent_profiles(profile_id), profile_revision_id text not null references agent_profile_revisions(profile_revision_id), selected_at timestamp not null)`,
	`create table project_profile_defaults(project_profile_default_id text primary key, project_id text not null references projects(project_id), profile_id text not null references agent_profiles(profile_id), created_at timestamp not null)`,
	`create table workspaces(workspace_id text primary key, workspace_key text not null unique, project_id text not null references projects(project_id), repository_id text not null references repositories(repository_id), host_id text not null references hosts(host_id), path text not null, created_at timestamp not null, closed_at timestamp null)`,
	`create table project_root_workspaces(project_root_workspace_id text primary key, workspace_id text not null unique references workspaces(workspace_id), created_at timestamp not null)`,
	`create table managed_worktrees(managed_worktree_id text primary key, workspace_id text not null unique references workspaces(workspace_id), branch_name text not null, base_ref text not null, base_sha text not null, initial_head_sha text not null, marker_file_path text not null, marker_file_hash text not null, created_at timestamp not null)`,
	`create table active_worktrees(active_worktree_id text primary key, managed_worktree_id text not null unique references managed_worktrees(managed_worktree_id), published_at timestamp not null)`,
	`create table closing_worktrees(closing_worktree_id text primary key, managed_worktree_id text not null unique references managed_worktrees(managed_worktree_id), close_attempt_id text not null references close_attempts(close_attempt_id), memo_json json not null, created_at timestamp not null)`,
	`create table removed_worktrees(removed_worktree_id text primary key, managed_worktree_id text not null unique references managed_worktrees(managed_worktree_id), removed_at timestamp not null, removal_reason_json json not null)`,
	`create table tmux_servers(tmux_server_id text primary key, tmux_server_key text not null unique, host_id text not null references hosts(host_id), socket_spec_json json not null, server_identity_json json null, created_at timestamp not null, retired_at timestamp null)`,
	`create table tmux_targets(tmux_target_id text primary key, tmux_target_key text not null unique, host_id text not null references hosts(host_id), tmux_server_id text not null references tmux_servers(tmux_server_id), target_spec_json json not null, created_at timestamp not null, retired_at timestamp null)`,
	`create table agent_sessions(session_id text primary key, session_key text not null unique, project_id text not null references projects(project_id), workspace_id text not null references workspaces(workspace_id), profile_revision_id text not null references agent_profile_revisions(profile_revision_id), host_id text not null references hosts(host_id), title text not null, created_at timestamp not null, closed_at timestamp null)`,
	`create table session_tmux_targets(session_tmux_target_id text primary key, session_id text not null references agent_sessions(session_id), tmux_target_id text not null references tmux_targets(tmux_target_id), attached_at timestamp not null, detached_at timestamp null)`,
	`create table agent_runs(run_id text primary key, session_id text not null references agent_sessions(session_id), run_seq integer not null, launch_argv_json json not null, launch_env_json json not null, working_directory text not null, requested_at timestamp not null, started_at timestamp null)`,
	`create table active_runner_bindings(runner_binding_id text primary key, run_id text not null unique references agent_runs(run_id), tmux_target_id text not null references tmux_targets(tmux_target_id), runner_endpoint_json json not null, runner_protocol_version integer not null, runner_binary_version text not null, process_group_ref text null, last_heartbeat_at timestamp not null, bound_at timestamp not null)`,
	`create table run_terminal_outcomes(run_terminal_outcome_id text primary key, run_id text not null unique references agent_runs(run_id), outcome text not null, termination_json json not null, occurred_at timestamp not null)`,
	`create table runner_output_chunks(runner_output_chunk_id text primary key, run_id text not null references agent_runs(run_id), chunk_seq integer not null, stream text not null, content_ref_json json not null, captured_at timestamp not null)`,
	`create table run_input_events(run_input_event_id text primary key, run_id text not null references agent_runs(run_id), input_seq integer not null, input_ref_json json not null, delivery_json json not null, created_at timestamp not null)`,
	`create table status_subjects(status_subject_id text primary key, subject_json json not null, subject_hash text not null unique, created_at timestamp not null)`,
	`create table status_snapshots(status_snapshot_id text primary key, status_subject_id text not null references status_subjects(status_subject_id), captured_at timestamp not null, source text not null, snapshot_hash text not null, snapshot_json json not null)`,
	`create table latest_status_snapshots(status_subject_id text primary key references status_subjects(status_subject_id), status_snapshot_id text not null references status_snapshots(status_snapshot_id), updated_at timestamp not null)`,
	`create table safety_policies(safety_policy_id text primary key, safety_policy_key text not null unique, policy_json json not null, created_at timestamp not null, archived_at timestamp null)`,
	`create table safety_check_runs(safety_check_run_id text primary key, safety_policy_id text not null references safety_policies(safety_policy_id), status_subject_id text not null references status_subjects(status_subject_id), check_kind text not null, started_at timestamp not null, completed_at timestamp null, failed_at timestamp null, failure_json json null)`,
	`create table safety_check_findings(safety_check_finding_id text primary key, safety_check_run_id text not null references safety_check_runs(safety_check_run_id), blocker text null, severity text not null, location_json json not null, message text not null, evidence_json json not null, created_at timestamp not null)`,
	`create table close_attempts(close_attempt_id text primary key, close_attempt_key text not null unique, target_json json not null, requested_by_actor_json json not null, requested_at timestamp not null, completed_at timestamp null, failed_at timestamp null, failure_json json null)`,
	`create table close_blockers(close_blocker_id text primary key, close_attempt_id text not null references close_attempts(close_attempt_id), blocker text not null, summary text not null, evidence_json json not null, created_at timestamp not null)`,
	`create table events(event_id text primary key, status_subject_id text not null references status_subjects(status_subject_id), event_seq integer not null, occurred_at timestamp not null, event_type text not null, actor_json json not null, payload_json json not null, correlation_json json not null, causation_event_id text null references events(event_id))`,
	`create table notification_channels(notification_channel_id text primary key, notification_channel_key text not null unique, channel_type text not null, channel_spec_json json not null, created_at timestamp not null, disabled_at timestamp null)`,
	`create table notification_deliveries(notification_delivery_id text primary key, notification_channel_id text not null references notification_channels(notification_channel_id), event_id text not null references events(event_id), attempt_seq integer not null, attempted_at timestamp not null, delivered_at timestamp null, failed_at timestamp null, failure_json json null)`,
	`create table idempotency_keys(idempotency_key_id text primary key, replay_key text not null unique, operation_key text not null, request_hash text not null, result_ref_json json null, state text not null, created_at timestamp not null, completed_at timestamp null)`,
	`create unique index project_repositories_project_role_uq on project_repositories(project_id, role)`,
	`create unique index provider_models_provider_model_uq on provider_models(provider_id, model_key)`,
	`create unique index agent_profile_revisions_profile_seq_uq on agent_profile_revisions(profile_id, revision_seq)`,
	`create unique index project_profile_defaults_project_uq on project_profile_defaults(project_id)`,
	`create unique index agent_runs_session_seq_uq on agent_runs(session_id, run_seq)`,
	`create unique index runner_output_chunks_run_seq_uq on runner_output_chunks(run_id, chunk_seq)`,
	`create unique index run_input_events_run_seq_uq on run_input_events(run_id, input_seq)`,
	`create unique index events_subject_seq_uq on events(status_subject_id, event_seq)`,
	`create unique index notification_deliveries_channel_event_uq on notification_deliveries(notification_channel_id, event_id)`,
	`create unique index session_tmux_targets_session_active_uq on session_tmux_targets(session_id) where detached_at is null`,
	`create unique index session_tmux_targets_target_active_uq on session_tmux_targets(tmux_target_id) where detached_at is null`,
	`create index projects_archived_created_idx on projects(archived_at, created_at)`,
	`create index repositories_archived_key_idx on repositories(archived_at, repository_key)`,
	`create index hosts_archived_key_idx on hosts(archived_at, host_key)`,
	`create index workspaces_project_closed_created_idx on workspaces(project_id, closed_at, created_at)`,
	`create index workspaces_host_path_idx on workspaces(host_id, path)`,
	`create index agent_sessions_project_closed_created_idx on agent_sessions(project_id, closed_at, created_at)`,
	`create index agent_sessions_workspace_closed_idx on agent_sessions(workspace_id, closed_at)`,
	`create index agent_sessions_host_closed_idx on agent_sessions(host_id, closed_at)`,
	`create index agent_runs_session_requested_idx on agent_runs(session_id, requested_at)`,
	`create index active_runner_bindings_heartbeat_idx on active_runner_bindings(last_heartbeat_at)`,
	`create index active_runner_bindings_tmux_target_idx on active_runner_bindings(tmux_target_id)`,
	`create index session_tmux_targets_session_idx on session_tmux_targets(session_id)`,
	`create index session_tmux_targets_target_idx on session_tmux_targets(tmux_target_id)`,
	`create index config_revisions_source_idx on config_revisions(config_source_id)`,
	`create index status_snapshots_subject_captured_idx on status_snapshots(status_subject_id, captured_at)`,
	`create index safety_check_runs_subject_started_idx on safety_check_runs(status_subject_id, started_at)`,
	`create index safety_check_findings_run_idx on safety_check_findings(safety_check_run_id)`,
	`create index close_attempts_requested_idx on close_attempts(requested_at)`,
	`create index close_blockers_attempt_idx on close_blockers(close_attempt_id)`,
	`create index events_occurred_idx on events(occurred_at)`,
	`create index events_subject_occurred_idx on events(status_subject_id, occurred_at)`,
	`create index events_type_occurred_idx on events(event_type, occurred_at)`,
	`create index events_causation_idx on events(causation_event_id)`,
	`create index notification_deliveries_event_idx on notification_deliveries(event_id)`,
}
